theme: jekyll-theme-minimal
title: Integration test clients
description: Small fast clients to run integration tests on various installations
logo: img/spider.jpg
lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  gfm_quirks: true