name: build-and-test
on: [push, pull_request]

jobs:
  build:
    defaults:
      run:
        working-directory: ./rabbitmq
    strategy:
      matrix:
        go-version: [ 1.15.x, 1.16.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Download modules
        run:  go mod download -json

      - name: Build linux
        run: make build.linux

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          args: --timeout 10m
          working-directory: ./rabbitmq
