name: build-and-test
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.16
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Download modules
        run: go mod download -json

      - name: Build
        run: make build

  check:
    runs-on: ubuntu-latest
    container:
      image: golang:1.16
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.28
          args: --timeout 10m
