name: build-and-test
on: [push]

jobs:
  build:
    defaults:
      run:
        working-directory: ./rabbitmq
    strategy:
      matrix:
        go-version: [ 1.15.x, 1.16.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

#      - name: Lint
#        uses: golangci/golangci-lint-action@v2
#        with:
#          working-directory: it
#          version: v1.38
#          args: --timeout 15m

      - name: Download modules
        run:  go mod download -json

      - name: A
        shell: bash
        run: echo "version=$(./tag.sh)" >> $GITHUB_ENV

      - run: ./tag.sh

      - name: Build client binary
        run: make VERSION=${{ env.version }} build.linux

