name: build-and-test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.16
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Download modules
        working-directory: ./rabbitmq
        run:  go mod download -json

      - name: Build
        working-directory: ./rabbitmq
        run: make build

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.28
          args: --timeout 10m
          working-directory: ./rabbitmq
