name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: Ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Resolve dependencies
      run: go get ./...

    - name: Format
      run: go fmt rabbitmq/it/main.go
      
    - name: Vet
      run: go vet rabbitmq/it/main.go
      
    - name: Build
      run: go build -v ./rabbitmq/it/main.go
