name: Release
on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    name: Release nkdev
    runs-on: Ubuntu-latest
    needs: check
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set VERSION
        run: |
          export VERSION=$((git describe --tags --dirty --match='v*' 2>/dev/null || echo v0.0.0) | cut -c2- )
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - uses: actions/cache@v2
        env:
          cache-name: golang
        with:
          path: /go/pkg/mod
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-

      - name: Build release
        run: make -j3 -d release

      - name: Create GH release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            # Changelog

            ## Features :new:

            ## Fixed issues :zap:

            ## Improvements :+1:


