name: Release
on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    defaults:
      run:
        working-directory: ./rabbitmq
    strategy:
      matrix:
        go-version: [ 1.16 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    name: Release mq_test
    steps:
      - name: Install Go
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set VERSION
        run: |
          export VERSION=$((git describe --tags --dirty --match='v*' 2>/dev/null || echo v0.0.0) | cut -c2- )
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build release
        uses: actions/setup-go@v2
        run: make build.linux

     - name: Push to GitHub Packages
       uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: barkardk/integration/rabbitmq-client
          tag_with_ref: true
          path: ./rabbitmq


      - name: Create GH release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            # Changelog

            ## Features :new:

            ## Fixed issues :zap:

            ## Improvements :+1:


