name: build-edge-release
on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
jobs:
  build:
    defaults:
      run:
        working-directory: ./rabbitmq
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        env:
          cache-name: golang
        with:
          path: /go/pkg/mod
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-

      - name: Setup QUEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Set VERSION
        id: param
        run: |
          echo "version=$((git describe --tags --dirty --match='v*' 2>/dev/null || echo v0.0.0) | cut -c2- )" >> $GITHUB_ENV

      - name: Build docker container
        run:  |
          echo "${{ secrets.token }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          make VERSION=${{ env.version }} -j3 release
