name: Release
on:
  push:
    tags:
      - v*.*.*

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: version
        name: Configure Version
        run: |
          export VERSION=$((git describe --tags --dirty --match='v*' 2>/dev/null || echo v0.0.0) | cut -c2- )
          echo "Determined version ${VERSION} to use for the build"
          echo "::set-output name=version::${VERSION}"
    outputs:
      version: ${{ steps.version.outputs.version }}
  release:
    name: Release
    defaults:
      run:
        working-directory: ./rabbitmq
    strategy:
      matrix:
        go-version: [ 1.15 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    needs: setup
    env:
      VERSION: ${{ needs.setup.outputs.version }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io/barkardk
          username: ${{ github.actor  }}
          password: ${{ secrets.token }}

      - name: Build and deploy image
        run: make build
        env:
          VERSION: ${{ needs.setup.outputs.version }}
          REPOSITORY: ghcr.io/barkardk
          GITHUB_TOKEN: ${{ secrets.token }}

      - name: Create GH release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            # Changelog

            ## Features :new:

            ## Fixed issues :zap:

            ## Improvements :+1:


