name: Release
on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    defaults:
      run:
        working-directory: ./rabbitmq
    strategy:
      matrix:
        go-version: [ 1.15 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set VERSION
        run: |
          export VERSION=$((git describe --tags --dirty --match='v*' 2>/dev/null || echo v0.0.0) | cut -c2- )
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build release
        run: make build.linux

      - name: Set branch or tag name
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./rabbitmq
          tags: ghcr.io/barkardk/rabbitmq-client:${{ VERSION }}
          secrets: |
            GIT_AUTH_TOKEN=${{ github.token }}

      - name: Create GH release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            # Changelog

            ## Features :new:

            ## Fixed issues :zap:

            ## Improvements :+1:


